export default {
    "/dashboard": { "title": "Dashboard", "module": "@xaxay/portal/ui/dashboard", "default": true},
    "/app1": { "title": "app1", "module": "@xaxay/portal/ui/app1"},
    "/app2": { "title": "app2", "module": "@xaxay/portal/ui/app2"},
    "/app3": { "title": "app3", "module": "@xaxay/portal/ui/app3"},
    "/app4": { "title": "app4", "module": "@xaxay/portal/ui/app4"},
    "/app5": { "title": "app5", "module": "@xaxay/portal/ui/app5"},
    "/app6": { "title": "app6", "module": "@xaxay/portal/ui/app6"},
    "/app7": { "title": "app7", "module": "@xaxay/portal/ui/app7"},
    "/app8": { "title": "app8", "module": "@xaxay/portal/ui/app8"},
    "/app9": { "title": "app9", "module": "@xaxay/portal/ui/app9"},
    "/app10": { "title": "app10", "module": "@xaxay/portal/ui/app10"},
    "/app11": { "title": "app11", "module": "@xaxay/portal/ui/app11"},
    "/app12": { "title": "app12", "module": "@xaxay/portal/ui/app12"},
    "/app13": { "title": "app13", "module": "@xaxay/portal/ui/app13"},
    "/app14": { "title": "app14", "module": "@xaxay/portal/ui/app14"},
    "/app15": { "title": "app15", "module": "@xaxay/portal/ui/app15"},
    "/app16": { "title": "app16", "module": "@xaxay/portal/ui/app16"},
    "/app17": { "title": "app17", "module": "@xaxay/portal/ui/app17"},
    "/app18": { "title": "app18", "module": "@xaxay/portal/ui/app18"},
  }
  