export default {
    "/dashboard": { "title": "Dashboard", "module": "@xaxay/portal/ui/plugin/dashboard", "default": true, dashboard: false},
    "/app1": { "title": "app1", "module": "@xaxay/portal/ui/plugin/app1"},
    "/app2": { "title": "app2", "module": "@xaxay/portal/ui/plugin/app2"},
    "/app3": { "title": "app3", "module": "@xaxay/portal/ui/plugin/app3"},
    // "/app4": { "title": "app4", "module": "@xaxay/portal/ui/plugin/app4"},
    // "/app5": { "title": "app5", "module": "@xaxay/portal/ui/plugin/app5"},
    // "/app6": { "title": "app6", "module": "@xaxay/portal/ui/plugin/app6"},
    // "/app7": { "title": "app7", "module": "@xaxay/portal/ui/plugin/app7"},
    // "/app8": { "title": "app8", "module": "@xaxay/portal/ui/plugin/app8"},
    // "/app9": { "title": "app9", "module": "@xaxay/portal/ui/plugin/app9"},
    "/app10": { "title": "app10", "module": "@xaxay/portal/ui/plugin/app10"},
    // "/app11": { "title": "app11", "module": "@xaxay/portal/ui/plugin/app11"},
    // "/app12": { "title": "app12", "module": "@xaxay/portal/ui/plugin/app12"},
    "/app13": { "title": "app13", "module": "@xaxay/portal/ui/plugin/app13"},
    // "/app14": { "title": "app14", "module": "@xaxay/portal/ui/plugin/app14"},
    // "/app15": { "title": "app15", "module": "@xaxay/portal/ui/plugin/app15"},
    // "/app16": { "title": "app16", "module": "@xaxay/portal/ui/plugin/app16"},
    "/app17": { "title": "app17", "module": "@xaxay/portal/ui/plugin/app17"},
    // "/app18": { "title": "app18", "module": "@xaxay/portal/ui/plugin/app18"},
  }
  